name: job-scheduler
version: '0.1.0.0'
synopsis: Job Scheduler
description: See README.md
category: Job
author:
  - Chris Wilson
maintainer:
  - Chris Wilson <christopher.j.wilson@gmail.com>
copyright: "2017 Chris Wilson"
license: BSD3
license-file: LICENSE
extra-source-files:
  - README.md

ghc-options:
  - -Wall

dependencies:
  - base >=4.7 && <5
  - bytestring
  - http-types
  - mtl
  - scotty
  - stm
  - time
  - wai
  - wai-extra
  - warp
  - xml

library:
  source-dirs: src

executables:
  exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - job-scheduler